### ISSUE TITLE
Keep TDP after WakeUp from Hibernation

### ISSUE THREAD

**Issue by BassXX** [project-sbc/Power-Control-Panel#10]
Hello there!

After my GPD WIN 3 goes into hibernate, it does not restore the TDP i have set. Instead, it uses the System Defaults.

When rebooting, everything works fine. But it does not after the hibernation mode. I have set auto start on.

Thanks & Regards

**Comment by project-sbc** [comment]
Hey yeah I found the issue and fixed in 0.2.6 which releases sometime later today
