### ISSUE TITLE
Expose ability to set TDP through a shared DLL

### ISSUE THREAD

**Issue by joamjoamjoam** [project-sbc/Power-Control-Panel#11]
Hello I’m writing a plug-in for LaunchBox/Bigbox that will automatically set the TDP of windows PC handhelds when launching games/emulators etc. 

I’m missing the piece that sets the power levels on the different CPUs and I was wondering if it was possible to expose an interface to your program that would allow me to pass you TDP values to set. 

Even a command line interface would work. 

Thanks,
Trent Callan

**Comment by project-sbc** [comment]
i dont implement my own TDP control method here, I use rw.exe and ryzenadj to set TDP through command line.
