### ISSUE TITLE
Your CPU is not currently supported - i7-1065G7 

### ISSUE THREAD

**Issue by cjduble** [project-sbc/Power-Control-Panel#14]
My understanding is that Ice Lake is supported, but I'm unable to get Power Control Panel to work on my Razer Blade Stealth.  The exact message I get is "Your CPU is not currently supported. Please contact the developer on github to get your CPU added." 

My Log.log file:

"1/14/2022 9:14:30 PM Application started.
1/14/2022 9:14:36 PM Closing application
1/14/2022 9:14:36 PM Hiding unused rows"

I have installed windowsdesktop-runtime-5.0.8-win-x64 as well. 

EDIT: This happens on the most recent versions, but I went way back to 0.1.9 and that one does not give the same error FWIW

**Comment by caupro** [comment]
Hi, I talked to you through Discord, about an i7 1065g7. As there is this question in, open, I go this way

I using the 0.37 version

The Message error is:
"Your CPU is not currently supported. Please contact the developer on github with this message to request your cpu get added. Send this: Intel(r) Core(TM) i7-1065G7 CPU @1.30Ghz"

If I can help in any way let me know.

**Comment by project-sbc** [comment]
this software is not being supported anymore. find my latest here which supports this cpu
https://github.com/project-sbc/Power-Control-Panel-v2
