### ISSUE TITLE
More details on each setting, examples?

### ISSUE THREAD

**Issue by seamonkey420** [project-sbc/Power-Control-Panel#15]
Thanks for this cool app! Just was wondering since i'm somewhat new to intel cpus and power control, is is possible to explain in readme what each setting does?

I understand the TDP P1/P2 settings and Parked Cores but not sure what EPP or Power Balance CPU/GPU really mean.  I plan to do some researching on it more but thought i'd inquire.

thanks

**Comment by project-sbc** [comment]
this software is not being supported anymore. find my latest here:
https://github.com/project-sbc/Power-Control-Panel-v2
