### ISSUE TITLE
BUG:: RyzenAdj can crash the app

### ISSUE THREAD

**Issue by Cyberdyne12** [project-sbc/Power-Control-Panel#16]
Applying TDP too quickly to Ryzen APU's has a chance to crash the whole application. Log does leave an error. This is a known issue, but previous mitigations aren't effect enough.

I should also mention that it seems to crash even when only applying a single TDP profile, but this crash is a lot more rare. Edit: this seems to be related to applying profiles while the system is under high CPU/GPU usage.

**Comment by project-sbc** [comment]
I think we sorted this one out on discord? Closing
