### ISSUE TITLE
UI BUG::  Unparked Cores unhides itself

### ISSUE THREAD

**Issue by Cyberdyne12** [project-sbc/Power-Control-Panel#17]
Under Settings > Parameters, setting Unparked Cores to "No" will hide that setting in profile settings, which is the intended function. But the setting shows back up again in profiles after a restart. Parameters still says "No". 
I'm assuming this is a cosmetic issue, though I haven't tried using the Unparked Cores setting after it's set to "No".

**Comment by project-sbc** [comment]
this software is not being supported anymore. find my latest here:
https://github.com/project-sbc/Power-Control-Panel-v2
