### ISSUE TITLE
UI BUG:: GPU clock Status shows previous readout

### ISSUE THREAD

**Issue by Cyberdyne12** [project-sbc/Power-Control-Panel#18]
GPU clock under "Status" shows the core clock from the previously applied profile, not the current one. If you apply the profile twice you will see the correct GPU core clock under Status. This seems to be completely cosmetic, despite what is shown in Status... the GPU clock from the profile is correctly applied.

**Comment by project-sbc** [comment]
this software is not being supported anymore. find my latest here:
https://github.com/project-sbc/Power-Control-Panel-v2
