### ISSUE TITLE
Charging issue

### ISSUE THREAD

**Issue by gamester47** [project-sbc/Power-Control-Panel#2]
When the app is running I am unable to charge my device. As soon as I quit the app I am again able to charge. The device is an aya neo, amd Ryzen 5 4500U. I am running version 0.2.5, I also tested 0.2.4.

**Comment by project-sbc** [comment]
I receive my Aya Neo today. I’ll check it out. There is nothing in my program that could remotely prevent charging though. I only access read only API SystemParameters. PowerLineStatus which is read only. The charging circuit is dictated by firmware on the usb c controller and the battery fuel gauge IC, which CANNOT be modified without updating firmware.

**Comment by project-sbc** [comment]
Unreproducible bug, no further comment
