### ISSUE TITLE
Not supported cpu AMD laptop

### ISSUE THREAD

**Issue by DragonFrizzy** [project-sbc/Power-Control-Panel#20]
Hi could you please add support for AMD E1-1500 APU with Radeon(tm) HD Graphics
Gpu:Amd hd 7310

**Comment by Cyberdyne12** [comment]
I believe your APU is to old/low spec. This only supports Zen based APU's through Ryzenadj.

**Comment by project-sbc** [comment]
I’m in agreement with you, if you can try ryzenadj and report back your findings maybe I’ll consider adding it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DragonFrizzy** [comment]
Hi thank you very much for the reply when I tried running Ryzen adj it didn't want to run I will try tomorrow to run it again I didn't clearly understand what did you mean with report back your findings

**Comment by project-sbc** [comment]
RyzenAdj is a command line tool, you could try AATU or RMT to see if those work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DragonFrizzy** [comment]
Okay now I understand ATTU won't work I tried it already and RMT won't work too and left Ryzen Adj but I'm sure it won't work too it means bad luck sadly

**Comment by foemre** [comment]
@project-sbc How about zen 2 apus like 4700u? Will you add support for it? RMT works fine on 4700u btw, just asking out of curiosity.

**Comment by project-sbc** [comment]
original CPU is not supported

**Comment by project-sbc** [comment]
Oh sure I’ll add that later

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
