### ISSUE TITLE
AMD Ryzen 3 5300G not supported

### ISSUE THREAD

**Issue by GtiJason** [project-sbc/Power-Control-Panel#21]
Got a pop up Microsoft.Visualbasic.Core message requesting I send this message to ask for support for my "AMD Ryzen 3 5300G with Radeon Graphics"
I was using the latest Steamdeck supported version of 0.3.5

**Comment by project-sbc** [comment]
supported here: https://github.com/project-sbc/Power-Control-Panel-v2
