### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by Saad-Alareqi** [project-sbc/Power-Control-Panel#22]
Great and useful app. I have some ideas that might improve it a little more.
1- add new shortcuts to increase or decrease the tdp by 1+ or 1- and 5+ or 5-. with combination for example R1+L1+Right thumb up to increase...and so on.
2- when launching a game with a profile attached to it, add the ability to overwrite it with combination settings value. because currently when doing so it reverts back to the profile.
3- add in game overlay to show the tdp and other values like fps...etc. or if possible to control everything via in game overlay would be perfect, same as Aya neo app overlay

**Comment by project-sbc** [comment]
this software is not being supported anymore. find my latest here:
https://github.com/project-sbc/Power-Control-Panel-v2

some of these features are already available or will be added
