### ISSUE TITLE
Runs on Windows 11?

### ISSUE THREAD

**Issue by ReNNoN** [project-sbc/Power-Control-Panel#25]
hi men!

works on Windows11?

I've make a fresh install of W11 and now can't change tdp upper 28

onexplayer 1s

ty!!

**Comment by project-sbc** [comment]
So you can change tdp but can’t go above 28W?

**Comment by project-sbc** [comment]
You can’t go above 28W? I know the issue, my program only changes MMIO tdp, and not the MSR. MMIO is fine for lowering tdp but to go above you need to also apply MSR tdp change. I’ve learned how to do that and will incorporate into next big release
