### ISSUE TITLE
Driver can't be loaded on Windows 11 Beta ring

### ISSUE THREAD

**Issue by bschmidy10** [project-sbc/Power-Control-Panel#26]
It seems all of the tdp tools and .bat's fail to run properly on the windows 11 beta ring. The error appears on start and shows the driver fails to load.

**Comment by project-sbc** [comment]
Did you make sure core isolation is off?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: bschmidy10 ***@***.***>
Sent: Saturday, May 21, 2022 10:43:24 PM
To: project-sbc/Power-Control-Panel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel] Driver can't be loaded on Windows 11 Beta ring (Issue #26)


It seems all of the tdp tools and .bat's fail to run properly on the windows 11 beta ring. The error appears on start and shows the driver fails to load.

**Comment by project-sbc** [comment]
You are the 3rd or 4th person to mention this, I’ll dive into it to find out

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bschmidy10** [comment]
It has been confirmed in a couple discord servers for tools like this. Core
isolation is turned off, correct!

Hyatice says "wmic" is removed in the beta build which he thinks is causing
the problem.

Brendan Schmid

**Comment by project-sbc** [comment]
Can you check the debug or log file for rw.exe? Download a fresh copy of the portable version on the website and try to run iy

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by project-sbc** [comment]
Roll back to the latest stable released build. Beta builds cause rw.exe to crash. I alerted windows to this issue.

**Comment by plumlis** [comment]
Can't use it on Win 11 22h2

**Comment by project-sbc** [comment]
Yes that’s a known issue, Microsoft disabled the driver for rw. I’m not sure if that will carry forward into the public release

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by plumlis** [comment]
It seems its already in stable release.
I'm on Win11 22H2 RTM version.

**Comment by project-sbc** [comment]
I might have something, can you message me on discord?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by plumlis** [comment]
Fine, but how can I get in touch with you on discord?

**Comment by project-sbc** [comment]
My ID is ProjectSBC#9711

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by plumlis** [comment]
I already sent you a invitation on discord.
See you on there.

**Comment by project-sbc** [comment]
Good news, I think I found a different program that can do it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by plumlis** [comment]
Waiting for goodnews

**Comment by project-sbc** [comment]
Yes, I found an alternative and I’ve tested it, I need some time but I will have a windows 11 22h2 compatible solution. You will need to let windows defender accept this the first time. It did not like it, but at least it’s not completely unusable.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
