### ISSUE TITLE
When run exe nothing happens 

### ISSUE THREAD

**Issue by jaywhojaycee** [project-sbc/Power-Control-Panel#27]
When I run the exe nothing happens I’m on windows  11 using a onexplayer with amd 4800u

**Comment by simdolit** [comment]
> When I run the exe nothing happens I’m on windows 11 using a onexplayer with amd 4800u

Same for me using onexplayer  with intel  1195G7

**Comment by project-sbc** [comment]
this software is not being supported anymore. find my latest here:
https://github.com/project-sbc/Power-Control-Panel-v2
