### ISSUE TITLE
Status Issue

### ISSUE THREAD

**Issue by V4nkor** [project-sbc/Power-Control-Panel#3]
For some reason everything on the status tab exept for the profiles is indefinitly  labeled as "Loading" on my gpd win max.

**Comment by project-sbc** [comment]
What version are you running?

**Comment by V4nkor** [comment]
It is the 0.2.2 version

**Comment by project-sbc** [comment]
Download the latest, fixed in 0.2.4

**Comment by V4nkor** [comment]
Thanks !
