### ISSUE TITLE
Would you please implement a cli tool, or share the rw.exe command line arguments?

### ISSUE THREAD

**Issue by wkgcass** [project-sbc/Power-Control-Panel#30]
Hi, power-control-panel is a very useful tool.
It would be more helpful if this tool has a cli version.
I use playnite to manage my games, which supports script hooks. With the help of command line, I will be able to use different pl settings for different games.

BTW, If you are busy and cannot provide a cli solution, are you willing to share the rw.exe arguments?

**Comment by wkgcass** [comment]
I found the msr header file which is provided by Intel, and the documentation (however i'm not sure if it's the latest)
https://github.com/intel/powergov/blob/master/msr.h
https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-3b-part-2-manual.pdf

I believe what I have to do, is to read and set values at `0x638`(pp0) and `0x640`(pp1) ?
Am I correct?

**Comment by project-sbc** [comment]
Hey if you give it a little bit of time I’ll have everything open source. Rw is not supported on win 11 22h2 so I’ve switched now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wkgcass** [comment]
I did a bunch of resarch and found the correct way of reading/modifying power limit MSR for Alder Lake cpus (it should also work for older cpus in the past decade).

1. get `MSR_RAPL_POWER_UNIT (0x606)`
2. read `[3:0]` as an unsigned integer `u`, use `1/2^u Watts` as the power unit. e.g. on my platform, the value is `0011`, so the unit is `1/8 Watts`.
3. read `[19:16]` as an unsigned integer `t`, use `1/2^t Seconds` as the time unit. e.g. on my platform, the value is `1010`, so the unit is `1/2^10 Seconds`.
4. get or set `MSR_PKG_POWER_LIMIT (0x610)`. See ref 2 `Package RAPL Domain` for more info, arrange values corresponding to the documentation, and everything is done.

references:
1. [Intel® 64 and IA-32 Architectures Software Developer's Manual Volume 4: Model-Specific Registers](https://cdrdv2.intel.com/v1/dl/getContent/671098?explicitVersion=true&wapkw=model-specific%20register) It's weired, because in table 2-39 `610H` is not shown, instead there's `65CH` which is confusing and is not what I need. Anyway, use `610H` instead.
2. [Intel® 64 and IA-32 Architectures Software Developer's Manual Volume 3B: System Programming Guide, Part 2](https://cdrdv2.intel.com/v1/dl/getContent/671427?explicitVersion=true&wapkw=package%20rapl%20domain) see 14.10.1 for `RAPL Interfaces` and 14.10.3 for `Package RAPL Domain`

I'll read more docs about mmio, I believe it won't be too hard.
