### ISSUE TITLE
Not supported CPU AMD Ryzen 5 5600X 6-Core Procesor

### ISSUE THREAD

**Issue by TheBloodstomper** [project-sbc/Power-Control-Panel#31]
Hi, I'd be really interested in your app, that I would use inside an arcade cabinet and not an handle console, but my CPU isn't supported by your app. If you might give it a shot once, I'd be really happy of it! But if this kind of things comes out of your project, I'll totally understand.

Have a nice day and thanks for your work!

**Comment by project-sbc** [comment]
this software is not being supported anymore. find my latest here which likely supports this cpu:
https://github.com/project-sbc/Power-Control-Panel-v2

**Comment by project-sbc** [comment]
Hey! Working on v2 overhaul which will support 2nd gen onward, should be out in a week or so

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: TheBloodstomper ***@***.***>
Sent: Wednesday, July 6, 2022 5:32:19 PM
To: project-sbc/Power-Control-Panel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel] Not supported CPU AMD Ryzen 5 5600X 6-Core Procesor (Issue #31)


Hi, I'd be really interested in your app, that I would use inside an arcade cabinet and not an handle console, but my CPU isn't supported by your app. If you might give it a shot once, I'd be really happy of it! But if this kind of things comes out of your project, I'll totally understand.

Have a nice day and thanks for your work!
