### ISSUE TITLE
Not support AMD Athlon silver 3050e/3020e

### ISSUE THREAD

**Issue by plumlis** [project-sbc/Power-Control-Panel#35]
This Soc is used  on the Windows Game handheld Anbernic Win600.
Ryzen controller works with this devices.
I think this may can be supported.

**Comment by project-sbc** [comment]
supported here: https://github.com/project-sbc/Power-Control-Panel-v2

**Comment by project-sbc** [comment]
Hi yes, I’m working on v2 of the software and it will support any RyzenAdj cpus

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: plum ***@***.***>
Sent: Thursday, July 14, 2022 6:11:59 AM
To: project-sbc/Power-Control-Panel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel] Not support AMD Athlong silver 3050e/3020e (Issue #35)


This Soc is used on the Windows Game handheld Anbernic Win600.
Ryzen controller works with this devices.
I think this may can be supported.

**Comment by plumlis** [comment]
Thanks for your nice working.
I sold out my Win600 and getting steamdeck. So I can't test if it works.
But I think it shoud be work nicely.
