### ISSUE TITLE
Does not recognize installed .net runtime

### ISSUE THREAD

**Issue by dreamflasher** [project-sbc/Power-Control-Panel#37]
I have .net runtime installed with versions 3.5, 4, 5.0 and 6.0 but it still complains that .net is not installed.

**Comment by project-sbc** [comment]
Sorry I’m not supporting this project anymore.

Please use my latest project which has all the features and more: https://github.com/project-sbc/Power-Control-Panel-v2

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Marcel Ackermann ***@***.***>
Sent: Monday, October 3, 2022 3:53:40 AM
To: project-sbc/Power-Control-Panel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel] Does not recognize installed .net runtime (Issue #37)


I have .net runtime installed with versions 3.5, 4, 5.0 and 6.0 but it still complains that .net is not installed.

**Comment by project-sbc** [comment]
this software is not being supported anymore. find my latest here:
https://github.com/project-sbc/Power-Control-Panel-v2
