### ISSUE TITLE
Application does not appear when executed

### ISSUE THREAD

**Issue by ikuruga** [project-sbc/Power-Control-Panel#4]
On the Aya NEO.
Installed this before completing all of my windows updates.  It worked flawlessly. After I did the updates it did not,  so I system restored to before I updated.  Now when I run the exe it does nothing. Anyways, it's an awesome little app that's easy to use.  Unfortunately it seems that it isn't completely idiot proof.  Just thought I'd post this here for any future issue that it could contribute to.

**Comment by project-sbc** [comment]
Hey, could you please reach out to me via email or discord? I would like to investigate this further

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ikuruga ***@***.***>
Sent: Tuesday, July 6, 2021 4:09:52 PM
To: project-sbc/Power-Control-Panel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel] Application does not appear when executed (#4)


On the Aya NEO.
Installed this before completing all of my windows updates. It worked flawlessly. After I did the updates it did not, so I system restored to before I updated. Now when I run the exe it does nothing. Anyways, it's an awesome little app that's easy to use. Unfortunately it seems that it isn't completely idiot proof. Just thought I'd post this here for any future issue that it could contribute to.

**Comment by project-sbc** [comment]
When updating windows .net 5.0 can get uninstalled. Re-download .net 5.0
