### ISSUE TITLE
Driver cannot be loaded

### ISSUE THREAD

**Issue by richardoen286** [project-sbc/Power-Control-Panel#42]
Hey, I hope you're doing well. I wanted to reach out regarding an issue I've been facing with your app. Every time I try to use it, I keep getting hit with an error message saying "Driver cannot be loaded." Just to give you a heads up, I'm using an Intel Core i7-1165G7 CPU on my Lenovo Slim 3 14ITL6 laptop. I was really looking forward to using your app, especially for the TDP Level control feature, but this error is making it impossible to do anything. I've tried reinstalling it. Any help or insight you could provide to fix this would be awesome. Thanks a lot!

**Comment by project-sbc** [comment]
Hey! It’s an issue with rw.exe needing the driver to be unblocked. There is a quick instruction on the github page for this

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: richardoen286 ***@***.***>
Sent: Monday, February 26, 2024 8:22:17 AM
To: project-sbc/Power-Control-Panel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel] Driver cannot be loaded (Issue #42)


Hey, I hope you're doing well. I wanted to reach out regarding an issue I've been facing with your app. Every time I try to use it, I keep getting hit with an error message saying "Driver cannot be loaded." Just to give you a heads up, I'm using an Intel Core i7-1165G7 CPU on my Lenovo Slim 3 14ITL6 laptop. I was really looking forward to using your app, especially for the TDP Level control feature, but this error is making it impossible to do anything. I've tried reinstalling it. Any help or insight you could provide to fix this would be awesome. Thanks a lot!
