### ISSUE TITLE
Xinput values per profile

### ISSUE THREAD

**Issue by Nino-Bock** [project-sbc/Power-Control-Panel#6]
Is it possible to set different TDP values for R + L + DPAD per profile?
When playing lighter games I might want to toggle between different values than on heavy games.

So one profile has 
5,7,8,10
The other one has
10,15,20,25

That maybe helps optimizing battery.

**Comment by project-sbc** [comment]
Hello, there isn’t currently but I’m working on a new version and I’m trying to add overlay menus where you can do whatever you want to the tdp effortlessly
