### ISSUE TITLE
Profile priority - allow profile overwrite when one is already active

### ISSUE THREAD

**Issue by Nino-Bock** [project-sbc/Power-Control-Panel#8]
I propose to add a priority value to profiles.
That feature I consider advanced and not a must have, but rather a nice to have.

Program A starts. It has a profile attached to it with priority 10.
B starts. Its priority is also 10.
-> Nothing happens
Now C starts. It has a priority value of 11.
-> Profile for Program C is loaded
(C-closes -> Profile B gets loaded)

The use for such a feature would be game and media launcher like Steam, Kodi, Emulationstation...
When I start Steam I don't need high TDP and load the Steam profile.
Now a game launches that needs other TDP values I could assign a higher priority to that game and overwrite the Steam profile.

**Comment by project-sbc** [comment]
this software is not being supported anymore. find my latest here:
https://github.com/project-sbc/Power-Control-Panel-v2
