### ISSUE TITLE
Do changes to TDP persist between reboots?

### ISSUE THREAD

**Issue by trias702** [project-sbc/Power-Control-Panel#9]
Great programme, many thanks for releasing this! Just one quick question:

If I use this programme to change my AMD (Aya Neo) TDP to 10W, save all settings, close the programme, and then reboot the device, will the TDP naturally be 10W following the reboot? Or does the TDP reset to the BIOS default on a reboot, and then to enable the 10W TDP again, I would need to open this programme again after reboot and set the TDP to 10W?

Meaning, in order for TDP changes to persist between reboots, it is necessary to open the programme on every fresh Windows boot and re-apply the desired TDP settings?

**Comment by project-sbc** [comment]
Hey, so if you enable auto start in the settings, and make a default profile at 10w tdp, it will auto start the program at turn on AND apply that default profile

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: trias702 ***@***.***>
Sent: Saturday, July 17, 2021 5:42:53 PM
To: project-sbc/Power-Control-Panel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel] Do changes to TDP persist between reboots? (#9)


Great programme, many thanks for releasing this! Just one quick question:

If I use this programme to change my AMD (Aya Neo) TDP to 10W, save all settings, close the programme, and then reboot the device, will the TDP naturally be 10W following the reboot? Or does the TDP reset to the BIOS default on a reboot, and then to enable the 10W TDP again, I would need to open this programme again after reboot and set the TDP to 10W?

Meaning, in order for TDP changes to persist between reboots, it is necessary to open the programme on every fresh Windows boot and re-apply the desired TDP settings?

**Comment by project-sbc** [comment]
No follow up comment, closing
